### ISSUE TITLE
Add Discriminator Support for Polymorphic Types (Unions)

### ISSUE THREAD

**Issue by seandstewart** [seandstewart/typical#72]
### Description 

A common pattern for polymorphic data in statically typed languages is the use of a `discriminator` field on the object which can be used to determine which type to deserialize said data into. This is main use-case for users registering custom type deserializers in `typical`. A better route would be to expose a method at time of declaration by which the user my declare a discriminator.

### Potential Implementation

```python
from typing import ClassVar, Union
import typic

@typic.klass
class Something:
    type: ClassVar[str] = "something"


@typic.klass
class Else:
    type: ClassVar[str] = "else"


discriminator = typic.discriminator(field="type", mapping={"something": Something, "else": Else})


@typic.klass
class Poly:
    morphic: Union[Something, Else] = typic.field(discriminator=discriminator)

```

This relates to #56

**Comment by syastrov** [comment]
Another way would be to use literal types for the discriminator, as otherwise the variable could be mutated.

mypy just got support for narrowing tagged-unions: https://mypy.readthedocs.io/en/latest/literal_types.html#tagged-unions

I know explicit is better than implicit, but it would be cool if typic automatically could handle deserializing in this case: a union of objects each having exactly one field with the same name, which is annotated using a distinct literal type. I think that's pretty unambiguous what the behavior should be. :)

**Comment by seandstewart** [comment]
Now that mypy has defined the expected behavior, I think that's the way to go for sure.
