### ISSUE TITLE
Support for typing.Iterator and better support for typing.Iterable.

### ISSUE THREAD

**Issue by xbanke** [seandstewart/typical#94]
* typical version: 2.0.17
* Python version: 3.7.4
* Operating System:

### Description

Iterable can be infinitely.

```py

from typing import Iterable
import typic

def infinite_numbers():
    i = 0
    while 1:
        yield i
        i += 1

@typic.al
def foo(iterable: Iterable[int]):
    print(iterable)

foo(range(5))  # [0, 1, 2, 3, 4]
foo(infinite_numbers())  # never stop

```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by seandstewart** [comment]
Hey @xbanke -

Thanks for the submission. This is a tricky problem, because an `Iterable` may be an either an `Iterator` - which can iterate infinitely, or any iterable object/container.

As of right now, there's no existing support for iterators, so this would need to be added. 

I don't think I want to change the default behavior of `Iterable`, but perhaps some intelligence can be added once iterator support is added to try and detect which path to use based upon the input.
